#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/path_play"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/path_play/t1/2024_11_06_15_50_29-Darwin-arm64-path_play/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/path_play/path_play.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/path_play/t1/2024_11_06_15_50_29-Darwin-arm64-path_play/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/path_play/t1/2024_11_06_15_50_29-Darwin-arm64-path_play/t1.result"; export resultFn
testName="path_play"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/path_play/t1/2024_11_06_15_50_29-Darwin-arm64-path_play"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/path_play/t1/2024_11_06_15_50_29-Darwin-arm64-path_play/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/path_play/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core

     remove_generated_lmod_files

     runLmod --version                         # 1
     runLmod load A B                          # 2
     runLmod unload B                          # 3
     runLmod unload A                          # 3
     

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/path_play/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/path_play/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/path_play/t1/2024_11_06_15_50_29-Darwin-arm64-path_play/t1.result -t /Users/mcawood/Lmod/Lmod/rt/path_play/t1/2024_11_06_15_50_29-Darwin-arm64-path_play/t1.runtime results.csv
   