#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/i18n/t1/2024_10_17_14_37_12-Darwin-arm64-i18n/t1.result"; export resultFn
testName="i18n"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/i18n/i18n.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/i18n/t1/2024_10_17_14_37_12-Darwin-arm64-i18n/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/i18n/t1/2024_10_17_14_37_12-Darwin-arm64-i18n/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/i18n/t1/2024_10_17_14_37_12-Darwin-arm64-i18n/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/i18n"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/i18n/t1/2024_10_17_14_37_12-Darwin-arm64-i18n"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     runLmod --version                # 1
     runLmod avail                    # 2
     export LANG=es_ES
     runLmod avail                    # 3
     export LANG=de_DE
     runLmod avail                    # 4
     export LANG=fr_CA.UTF8
     runLmod avail                    # 5
     export LANG=pl
     runLmod avail                    # 6

     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/i18n/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core

     export LANG=zh
     runLmod load intel               # 6
     runLmod load gcc                 # 7
     export LANG=fr_CA.UTF8
     runLmod load unknown             # 8
     runLmod --help                   # 9



     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/i18n/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/i18n/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/i18n/t1/2024_10_17_14_37_12-Darwin-arm64-i18n/t1.result -t /Users/mcawood/Lmod/Lmod/rt/i18n/t1/2024_10_17_14_37_12-Darwin-arm64-i18n/t1.runtime results.csv
   