#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/tmod_spider/t1/2024_11_07_13_03_06-Darwin-arm64-tmod_spider/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/tmod_spider/t1/2024_11_07_13_03_06-Darwin-arm64-tmod_spider/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/tmod_spider"; export testDir
testName="tmod_spider"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/tmod_spider/t1/2024_11_07_13_03_06-Darwin-arm64-tmod_spider/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/tmod_spider/tmod_spider.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/tmod_spider/t1/2024_11_07_13_03_06-Darwin-arm64-tmod_spider"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/tmod_spider/t1/2024_11_07_13_03_06-Darwin-arm64-tmod_spider/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/tmod_spider/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core

     remove_generated_lmod_files
     mkdir -p .cache/lmod

     runLmod --version                                        # 1
     buildSpiderT $MODULEPATH > .cache/lmod/spiderT.lua       # 2
     runLmod avail                                            # 3


     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/tmod_spider/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/tmod_spider/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/tmod_spider/t1/2024_11_07_13_03_06-Darwin-arm64-tmod_spider/t1.result -t /Users/mcawood/Lmod/Lmod/rt/tmod_spider/t1/2024_11_07_13_03_06-Darwin-arm64-tmod_spider/t1.runtime results.csv
   