#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_06_15_50_29-Darwin-arm64-broken_modulerc/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/broken_modulerc.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_06_15_50_29-Darwin-arm64-broken_modulerc/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_06_15_50_29-Darwin-arm64-broken_modulerc/t1.result"; export resultFn
testName="broken_modulerc"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_06_15_50_29-Darwin-arm64-broken_modulerc"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_06_15_50_29-Darwin-arm64-broken_modulerc/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/.modulerc .

     runLmod --version                # 1
     runLmod use /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/mf/Core   # 2
     runLmod load git hdf5/1.8.15     # 3
     runLmod list                     # 4

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_06_15_50_29-Darwin-arm64-broken_modulerc/t1.result -t /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_06_15_50_29-Darwin-arm64-broken_modulerc/t1.runtime results.csv
   