#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/manpath/t1/2024_11_07_13_03_06-Darwin-arm64-manpath/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/manpath/t1/2024_11_07_13_03_06-Darwin-arm64-manpath/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/manpath"; export testDir
testName="manpath"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/manpath/t1/2024_11_07_13_03_06-Darwin-arm64-manpath/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/manpath/manpath.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/manpath/t1/2024_11_07_13_03_06-Darwin-arm64-manpath"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/manpath/t1/2024_11_07_13_03_06-Darwin-arm64-manpath/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/manpath/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core

     remove_generated_lmod_files

     runLmod --version                     # 1
     runLmod load   unix                   # 2
     runLmod unload unix                   # 3
     runLmod load   unix noweb             # 4
     runLmod unload noweb unix             # 5
     export MANPATH=/unknown/apps/junk/share/man
     runLmod load   unix                   # 6
     runLmod unload unix                   # 7
     export MANPATH=/opt/X/man:::/opt/Y/man
     runLmod load   abc                    # 8
     runLmod load   def                    # 9



     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/manpath/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/manpath/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/manpath/t1/2024_11_07_13_03_06-Darwin-arm64-manpath/t1.result -t /Users/mcawood/Lmod/Lmod/rt/manpath/t1/2024_11_07_13_03_06-Darwin-arm64-manpath/t1.runtime results.csv
   