#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/columnT"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/columnT/t1/2024_11_06_15_50_29-Darwin-arm64-columnT/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/columnT/columnT.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/columnT/t1/2024_11_06_15_50_29-Darwin-arm64-columnT/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/columnT/t1/2024_11_06_15_50_29-Darwin-arm64-columnT/t1.result"; export resultFn
testName="columnT"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/columnT/t1/2024_11_06_15_50_29-Darwin-arm64-columnT"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/columnT/t1/2024_11_06_15_50_29-Darwin-arm64-columnT/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/columnT/modules:/Users/mcawood/Lmod/Lmod/rt/columnT/modules-npa; export MODULEPATH


     remove_generated_lmod_files

     m1="
         "

     runLmod --version                    # 1
     runLmod avail                        # 2
     runLmod load mpi.zlib.hdf5.netcdf    # 3
     runLmod load python2.7.cython.numpy.scipy.numexpr.scientific.matplotlib #4
     runLmod load fftw/2.1.5 grace/5.1.23 # 5
     runLmod list                         # 6
     runLmod --mt                         # 7

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/columnT/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/columnT/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/columnT/t1/2024_11_06_15_50_29-Darwin-arm64-columnT/t1.result -t /Users/mcawood/Lmod/Lmod/rt/columnT/t1/2024_11_06_15_50_29-Darwin-arm64-columnT/t1.runtime results.csv
   