#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/extended_default/t1/2024_11_07_13_03_06-Darwin-arm64-extended_default/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/extended_default/t1/2024_11_07_13_03_06-Darwin-arm64-extended_default/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/extended_default"; export testDir
testName="extended_default"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/extended_default/t1/2024_11_07_13_03_06-Darwin-arm64-extended_default/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/extended_default/extended_default.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/extended_default/t1/2024_11_07_13_03_06-Darwin-arm64-extended_default"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/extended_default/t1/2024_11_07_13_03_06-Darwin-arm64-extended_default/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/extended_default/mf/Core

     remove_generated_lmod_files

     runLmod --version                         # 1
     runLmod load intel/1                      # 2
     runLmod load mcr/64/1                     # 3
     runLmod load intel/17                     # 4
     runLmod load mcr/64/18                    # 5
     runLmod load petsc/3                      # 6
     runLmod load gcc-ftn/10.1                 # 7
     runLmod load junk/4.0.2                   # 8
     runLmod list                              # 9
     runLmod load junk/4.0.2-i                 #10
     runLmod list                              #11
     runLmod purge                             #12
     runLmod load abc/2                        #13
     runLmod list                              #14
     runLmod purge                             #15
     runLmod load A/10                         #16
     runLmod refresh                           #17
     runLmod list                              #18






     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/extended_default/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/extended_default/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/extended_default/t1/2024_11_07_13_03_06-Darwin-arm64-extended_default/t1.result -t /Users/mcawood/Lmod/Lmod/rt/extended_default/t1/2024_11_07_13_03_06-Darwin-arm64-extended_default/t1.runtime results.csv
   