#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/t1/2024_11_06_15_50_29-Darwin-arm64-sh_to_modulefile/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/sh_to_modulefile.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/t1/2024_11_06_15_50_29-Darwin-arm64-sh_to_modulefile/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/t1/2024_11_06_15_50_29-Darwin-arm64-sh_to_modulefile/t1.result"; export resultFn
testName="sh_to_modulefile"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/t1/2024_11_06_15_50_29-Darwin-arm64-sh_to_modulefile"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/t1/2024_11_06_15_50_29-Darwin-arm64-sh_to_modulefile/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/mf; export MODULEPATH

     remove_generated_lmod_files s.log 

     unset -f fooBar > /dev/null 2> /dev/null

     runLmod --version                                 # 1
     runSh2MF             /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/tstScript.sh      # 2
     runSh2MF  --to TCL   /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/tstScript.sh      # 3 
     runSh2MF             /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/path_both_ends.sh # 4        
     runSh2MF  --from csh /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/cshScript.csh     # 5
     runSh2MF             /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/broken.sh         # 6
     runSh2MF             /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/unalias.sh        # 7 
     runLmod  show wrapperSh/1.0                       # 8
     runLmod  load wrapperSh/1.0                       # 9
     runLmod  show wrapperSh/1.0                       #10
     runLmod  refresh                                  #11
     runLmod  list                                     #12
     runLmod  --mt                                     #13
     runLmod  unload wrapperSh/1.0                     #14
     runLmod  load   brokenSh/1.0                      #15
     runLmod  load   wrapperSh/1.0                     #16
     runLmod  save                                     #18
     runLmod  restore                                  #19
     runLmod  --mt                                     #20

     unsetMT

     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/t1/2024_11_06_15_50_29-Darwin-arm64-sh_to_modulefile/mf; export MODULEPATH
     mkdir -p $MODULEPATH/A

     buildSh2MF  --to TCL   /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/tstScript.sh > $MODULEPATH/A/1.0
     runLmod load A                                    #20
     runLmod list                                      #21

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/t1/2024_11_06_15_50_29-Darwin-arm64-sh_to_modulefile/t1.result -t /Users/mcawood/Lmod/Lmod/rt/sh_to_modulefile/t1/2024_11_06_15_50_29-Darwin-arm64-sh_to_modulefile/t1.runtime results.csv
   