#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_10_17_14_37_12-Darwin-arm64-p4est/t1.result"; export resultFn
testName="p4est"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/p4est/p4est.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_10_17_14_37_12-Darwin-arm64-p4est/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_10_17_14_37_12-Darwin-arm64-p4est/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_10_17_14_37_12-Darwin-arm64-p4est/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/p4est"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_10_17_14_37_12-Darwin-arm64-p4est"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars

     remove_generated_lmod_files

     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/p4est/mf/Core:/Users/mcawood/Lmod/Lmod/rt/p4est/mf/User

     runLmod --version               # 1
     runLmod av                      # 2
     runLmod --show_hidden av        # 3
     runLmod load p4est              # 4
     runLmod load local              # 5
     runLmod list                    # 6

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/p4est/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/p4est/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_10_17_14_37_12-Darwin-arm64-p4est/t1.result -t /Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_10_17_14_37_12-Darwin-arm64-p4est/t1.runtime results.csv
   