#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/user_inherit/t1/2024_10_17_14_37_12-Darwin-arm64-user_inherit/t1.result"; export resultFn
testName="user_inherit"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/user_inherit/user_inherit.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/user_inherit/t1/2024_10_17_14_37_12-Darwin-arm64-user_inherit/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/user_inherit/t1/2024_10_17_14_37_12-Darwin-arm64-user_inherit/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/user_inherit/t1/2024_10_17_14_37_12-Darwin-arm64-user_inherit/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/user_inherit"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/user_inherit/t1/2024_10_17_14_37_12-Darwin-arm64-user_inherit"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/user_inherit/mf;         export MODULEPATH_ROOT
     MY_MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/user_inherit/user_mf;  export MY_MODULEPATH_ROOT

     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/user_inherit/user_mf/Core:/Users/mcawood/Lmod/Lmod/rt/user_inherit/mf/Core

     RTM_SETTARG_CMD=":";               export RTM_SETTARG_CMD

     remove_generated_lmod_files

     runLmod --version        # 1
     runLmod avail            # 2
     runLmod load intel       # 3
     runLmod avail            # 4
     runLmod show intel       # 5
     runLmod help intel       # 6
     runLmod load boost       # 7
     runLmod list             # 8
     runLmod show pgi         # 9

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/user_inherit/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/user_inherit/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/user_inherit/t1/2024_10_17_14_37_12-Darwin-arm64-user_inherit/t1.result -t /Users/mcawood/Lmod/Lmod/rt/user_inherit/t1/2024_10_17_14_37_12-Darwin-arm64-user_inherit/t1.runtime results.csv
   