#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/hook"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/hook/t1/2024_11_06_15_50_29-Darwin-arm64-hook/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/hook/hook.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/hook/t1/2024_11_06_15_50_29-Darwin-arm64-hook/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/hook/t1/2024_11_06_15_50_29-Darwin-arm64-hook/t1.result"; export resultFn
testName="hook"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/hook/t1/2024_11_06_15_50_29-Darwin-arm64-hook"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/hook/t1/2024_11_06_15_50_29-Darwin-arm64-hook/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/hook/mf;     export MODULEPATH_ROOT
     LMOD_PREPEND_BLOCK=yes;            export LMOD_PREPEND_BLOCK

     export LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/hook/orig_hook_style; 

     remove_generated_lmod_files

     runLmod --version                      # 1
     runLmod use -a /Users/mcawood/Lmod/Lmod/rt/hook/mf/Core      # 2
     runLmod load admin intel               # 3
     export LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/hook/replace
     runLmod load admin intel               # 4
     export LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/hook/append
     runLmod load admin intel               # 5
     export LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/hook/prepend
     runLmod load admin intel               # 6

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/hook/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/hook/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/hook/t1/2024_11_06_15_50_29-Darwin-arm64-hook/t1.result -t /Users/mcawood/Lmod/Lmod/rt/hook/t1/2024_11_06_15_50_29-Darwin-arm64-hook/t1.runtime results.csv
   