#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/fish"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/fish/t1/2024_11_06_15_50_29-Darwin-arm64-fish/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/fish/fish.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/fish/t1/2024_11_06_15_50_29-Darwin-arm64-fish/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/fish/t1/2024_11_06_15_50_29-Darwin-arm64-fish/t1.result"; export resultFn
testName="fish"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/fish/t1/2024_11_06_15_50_29-Darwin-arm64-fish"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/fish/t1/2024_11_06_15_50_29-Darwin-arm64-fish/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh
     unsetMT
     initStdEnvVars
     export LMOD_TERM_WIDTH=150
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/fish/mf;  export MODULEPATH_ROOT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/fish/mf/Core
     export MODULEPATH
     unset TERM

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua


     runFish --version                # 1
     runFish load intel               # 2


     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -fish  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/fish/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/fish/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/fish/t1/2024_11_06_15_50_29-Darwin-arm64-fish/t1.result -t /Users/mcawood/Lmod/Lmod/rt/fish/t1/2024_11_06_15_50_29-Darwin-arm64-fish/t1.runtime results.csv
   