#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_07_13_03_06-Darwin-arm64-broken_modulerc/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_07_13_03_06-Darwin-arm64-broken_modulerc/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc"; export testDir
testName="broken_modulerc"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_07_13_03_06-Darwin-arm64-broken_modulerc/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/broken_modulerc.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_07_13_03_06-Darwin-arm64-broken_modulerc"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_07_13_03_06-Darwin-arm64-broken_modulerc/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/.modulerc .

     runLmod --version                # 1
     runLmod use /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/mf/Core   # 2
     runLmod load git hdf5/1.8.15     # 3
     runLmod list                     # 4

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_07_13_03_06-Darwin-arm64-broken_modulerc/t1.result -t /Users/mcawood/Lmod/Lmod/rt/broken_modulerc/t1/2024_11_07_13_03_06-Darwin-arm64-broken_modulerc/t1.runtime results.csv
   