#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/find_first/t1/2024_11_07_13_03_06-Darwin-arm64-find_first/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/find_first/t1/2024_11_07_13_03_06-Darwin-arm64-find_first/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/find_first"; export testDir
testName="find_first"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/find_first/t1/2024_11_07_13_03_06-Darwin-arm64-find_first/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/find_first/find_first.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/find_first/t1/2024_11_07_13_03_06-Darwin-arm64-find_first"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/find_first/t1/2024_11_07_13_03_06-Darwin-arm64-find_first/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/find_first/mf1:/Users/mcawood/Lmod/Lmod/rt/find_first/mf2

     remove_generated_lmod_files

     runLmod --version                         # 1
     runLmod load a                            # 2
     runLmod list                              # 3
     runLmod delete a                          # 4

     export LMOD_TMOD_FIND_FIRST=yes
     runLmod load a                            # 2
     runLmod list                              # 3

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/find_first/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/find_first/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/find_first/t1/2024_11_07_13_03_06-Darwin-arm64-find_first/t1.result -t /Users/mcawood/Lmod/Lmod/rt/find_first/t1/2024_11_07_13_03_06-Darwin-arm64-find_first/t1.runtime results.csv
   