#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/properties"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/properties/t1/2024_11_06_15_50_29-Darwin-arm64-properties/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/properties/properties.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/properties/t1/2024_11_06_15_50_29-Darwin-arm64-properties/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/properties/t1/2024_11_06_15_50_29-Darwin-arm64-properties/t1.result"; export resultFn
testName="properties"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/properties/t1/2024_11_06_15_50_29-Darwin-arm64-properties"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/properties/t1/2024_11_06_15_50_29-Darwin-arm64-properties/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/properties/mf;     export MODULEPATH_ROOT

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua
     mkdir -p .cache/lmod

     runLmod --version                  # 1
     runLmod use -a /Users/mcawood/Lmod/Lmod/rt/properties/mf/Core  # 2
     runLmod use -a /Users/mcawood/Lmod/Lmod/rt/properties/mf/bio   # 3
     runLmod use -a /Users/mcawood/Lmod/Lmod/rt/properties/mf/cae   # 4
     runLmod load PrgEnv                # 5
     runLmod list                       # 6
     buildSpiderT   $MODULEPATH > ~/.cache/lmod/spiderT.lua
     runLmod avail                      # 7


     HOME=$ORIG_HOME



     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/properties/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/properties/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/properties/t1/2024_11_06_15_50_29-Darwin-arm64-properties/t1.result -t /Users/mcawood/Lmod/Lmod/rt/properties/t1/2024_11_06_15_50_29-Darwin-arm64-properties/t1.runtime results.csv
   