#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/p4est"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_11_06_15_50_29-Darwin-arm64-p4est/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/p4est/p4est.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_11_06_15_50_29-Darwin-arm64-p4est/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_11_06_15_50_29-Darwin-arm64-p4est/t1.result"; export resultFn
testName="p4est"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_11_06_15_50_29-Darwin-arm64-p4est"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_11_06_15_50_29-Darwin-arm64-p4est/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars

     remove_generated_lmod_files

     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/p4est/mf/Core:/Users/mcawood/Lmod/Lmod/rt/p4est/mf/User

     runLmod --version               # 1
     runLmod av                      # 2
     runLmod --show_hidden av        # 3
     runLmod load p4est              # 4
     runLmod load local              # 5
     runLmod list                    # 6

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/p4est/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/p4est/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_11_06_15_50_29-Darwin-arm64-p4est/t1.result -t /Users/mcawood/Lmod/Lmod/rt/p4est/t1/2024_11_06_15_50_29-Darwin-arm64-p4est/t1.runtime results.csv
   