#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/rstats"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/rstats/t1/2024_11_06_15_50_29-Darwin-arm64-rstats/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/rstats/rstats.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/rstats/t1/2024_11_06_15_50_29-Darwin-arm64-rstats/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/rstats/t1/2024_11_06_15_50_29-Darwin-arm64-rstats/t1.result"; export resultFn
testName="rstats"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/rstats/t1/2024_11_06_15_50_29-Darwin-arm64-rstats"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/rstats/t1/2024_11_06_15_50_29-Darwin-arm64-rstats/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/rstats/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core

     remove_generated_lmod_files

     runLmod --version                         # 1
     runLmod -T load Rpkgs                     # 2
     runLmod list                              # 3
     runLmod -T unload Rpkgs                   # 4


     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/rstats/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/rstats/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/rstats/t1/2024_11_06_15_50_29-Darwin-arm64-rstats/t1.result -t /Users/mcawood/Lmod/Lmod/rt/rstats/t1/2024_11_06_15_50_29-Darwin-arm64-rstats/t1.runtime results.csv
   