#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/noTCL"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/noTCL/t1/2024_11_06_15_50_29-Darwin-arm64-noTCL/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/noTCL/noTCL.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/noTCL/t1/2024_11_06_15_50_29-Darwin-arm64-noTCL/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/noTCL/t1/2024_11_06_15_50_29-Darwin-arm64-noTCL/t1.result"; export resultFn
testName="noTCL"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/noTCL/t1/2024_11_06_15_50_29-Darwin-arm64-noTCL"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/noTCL/t1/2024_11_06_15_50_29-Darwin-arm64-noTCL/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/noTCL/mf;   export MODULEPATH_ROOT
     MODULEPATH=$MODULEPATH_ROOT/Core:$MODULEPATH_ROOT/TACC
     export MODULEPATH
     LMOD_DEFAULT_MODULEPATH=$MODULEPATH
     export LMOD_DEFAULT_MODULEPATH
     export LMOD_ALLOW_TCL_MFILES=no;

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     runLmod --version                                      # 1
     runLmod avail                                          # 2
     runLmod spider                                         # 3
     runLmod load   PrgEnv                                  # 4
     runLmod unload PrgEnv                                  # 5
     buildSpiderT $LMOD_DEFAULT_MODULEPATH > $HOME/.cache/lmod/spiderT.lua
     runLmod load   PrgEnv                                  # 6




     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/noTCL/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/noTCL/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/noTCL/t1/2024_11_06_15_50_29-Darwin-arm64-noTCL/t1.result -t /Users/mcawood/Lmod/Lmod/rt/noTCL/t1/2024_11_06_15_50_29-Darwin-arm64-noTCL/t1.runtime results.csv
   