#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/bioContainers/t1/2024_10_17_14_37_12-Darwin-arm64-bioContainers/t1.result"; export resultFn
testName="bioContainers"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/bioContainers/bioContainers.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/bioContainers/t1/2024_10_17_14_37_12-Darwin-arm64-bioContainers/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/bioContainers/t1/2024_10_17_14_37_12-Darwin-arm64-bioContainers/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/bioContainers/t1/2024_10_17_14_37_12-Darwin-arm64-bioContainers/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/bioContainers"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/bioContainers/t1/2024_10_17_14_37_12-Darwin-arm64-bioContainers"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/bioContainers/mf/
     export MODULEPATH=$MODULEPATH_ROOT/Core
     export BCDMF=/Users/mcawood/Lmod/Lmod/rt/bioContainers/bcd/mf

     remove_generated_lmod_files bcd cacheDir

     runLmod --version                                # 1
     mkdir -p bcd/cacheDir cacheDir

     export LMOD_RC=/Users/mcawood/Lmod/Lmod/rt/bioContainers/lmodrc.lua
     touch bcd/timestamp
     buildSpiderT $BCDMF > bcd/cacheDir/spiderT.lua

     runLmod avail                                    # 2
     runLmod load bioContainers                       # 3
     runLmod -T avail                                 # 4


     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/bioContainers/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/bioContainers/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/bioContainers/t1/2024_10_17_14_37_12-Darwin-arm64-bioContainers/t1.result -t /Users/mcawood/Lmod/Lmod/rt/bioContainers/t1/2024_10_17_14_37_12-Darwin-arm64-bioContainers/t1.runtime results.csv
   