#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/help/t1/2024_11_07_13_03_06-Darwin-arm64-help/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/help/t1/2024_11_07_13_03_06-Darwin-arm64-help/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/help"; export testDir
testName="help"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/help/t1/2024_11_07_13_03_06-Darwin-arm64-help/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/help/help.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/help/t1/2024_11_07_13_03_06-Darwin-arm64-help"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/help/t1/2024_11_07_13_03_06-Darwin-arm64-help/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/help/mf;            export MODULEPATH

     remove_generated_lmod_files config.json

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     runLmod --version                                        # 1
     runLmod --help                                           # 2
     runLmod help                                             # 3
     runLmod help amber                                       # 4
     runLmod --config                                         # 5
     runLmod --miniConfig                                     # 6
     runLmod --pod                                            # 7
     LD_PRELOAD= $LUA_EXEC $projectDir/src/lmod.in.lua bash --config_json 2> config.json
     runBase $LUA_EXEC $projectDir/src/chkJson < config.json  # 8


     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/help/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/help/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/help/t1/2024_11_07_13_03_06-Darwin-arm64-help/t1.result -t /Users/mcawood/Lmod/Lmod/rt/help/t1/2024_11_07_13_03_06-Darwin-arm64-help/t1.runtime results.csv
   