#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/tclmodules"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/tclmodules/t1/2024_11_06_15_50_29-Darwin-arm64-tclmodules/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/tclmodules/tclmodules.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/tclmodules/t1/2024_11_06_15_50_29-Darwin-arm64-tclmodules/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/tclmodules/t1/2024_11_06_15_50_29-Darwin-arm64-tclmodules/t1.result"; export resultFn
testName="tclmodules"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/tclmodules/t1/2024_11_06_15_50_29-Darwin-arm64-tclmodules"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/tclmodules/t1/2024_11_06_15_50_29-Darwin-arm64-tclmodules/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/tclmodules/mf
     export FOO=BAR

     remove_generated_lmod_files

     runLmod --version                         # 1
     runLmod whatis a                          # 2
     runLmod load   earlyLateOutput            # 3
     runLmod list                              # 4
     runLmod show showMe                       # 5
     runLmod avail                             # 6
     runLmod load getenv                       # 7

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/tclmodules/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/tclmodules/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/tclmodules/t1/2024_11_06_15_50_29-Darwin-arm64-tclmodules/t1.result -t /Users/mcawood/Lmod/Lmod/rt/tclmodules/t1/2024_11_06_15_50_29-Darwin-arm64-tclmodules/t1.runtime results.csv
   