#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/mpath"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/mpath/t1/2024_11_06_15_50_29-Darwin-arm64-mpath/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/mpath/mpath.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/mpath/t1/2024_11_06_15_50_29-Darwin-arm64-mpath/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/mpath/t1/2024_11_06_15_50_29-Darwin-arm64-mpath/t1.result"; export resultFn
testName="mpath"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/mpath/t1/2024_11_06_15_50_29-Darwin-arm64-mpath"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/mpath/t1/2024_11_06_15_50_29-Darwin-arm64-mpath/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/mpath/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core


     remove_generated_lmod_files

     runLmod --version                     # 1
     runLmod avail                         # 2
     MODULEPATH=$MODULEPATH_ROOT/RTM:$MODULEPATH
     runLmod avail                         # 3
     unsetMT
     MODULEPATH=$MODULEPATH_ROOT/Core
     runLmod avail                         # 4
     MODULEPATH=$MODULEPATH_ROOT/Core:$MODULEPATH_ROOT/RTM
     runLmod avail                         # 5
     runLmod load icc ifort                # 6
     runLmod unload icc                    # 7
     runLmod load icc                      # 8

     runLmod unuse $testDir/mf/Compiler/intel/18.0

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/mpath/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/mpath/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/mpath/t1/2024_11_06_15_50_29-Darwin-arm64-mpath/t1.result -t /Users/mcawood/Lmod/Lmod/rt/mpath/t1/2024_11_06_15_50_29-Darwin-arm64-mpath/t1.runtime results.csv
   