#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/nvv/t1/2024_10_17_14_37_12-Darwin-arm64-nvv/t1.result"; export resultFn
testName="nvv"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/nvv/nvv.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/nvv/t1/2024_10_17_14_37_12-Darwin-arm64-nvv/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/nvv/t1/2024_10_17_14_37_12-Darwin-arm64-nvv/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/nvv/t1/2024_10_17_14_37_12-Darwin-arm64-nvv/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/nvv"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/nvv/t1/2024_10_17_14_37_12-Darwin-arm64-nvv"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/nvv/mf

     remove_generated_lmod_files

     runLmod --version                         # 1
     runLmod avail                             # 2

     runLmod purge                             # 3
     unsetMT

     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/nvv/el1:/Users/mcawood/Lmod/Lmod/rt/nvv/el2
     runLmod load intel/17                     # 4
     runLmod list                              # 5

     runLmod purge                             # 6
     unsetMT

     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/nvv/bc/mf:/Users/mcawood/Lmod/Lmod/rt/nvv/bc/cm
     runLmod avail                             # 7
     runLmod load HPCBIOS/2015q2               # 8
     
     runLmod purge                             # 9
     unsetMT

     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/nvv/mf2:/Users/mcawood/Lmod/Lmod/rt/nvv/mf3
     runLmod avail                             #10
     runLmod load aaa                          #11
     runLmod list                              #12

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/nvv/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/nvv/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/nvv/t1/2024_10_17_14_37_12-Darwin-arm64-nvv/t1.result -t /Users/mcawood/Lmod/Lmod/rt/nvv/t1/2024_10_17_14_37_12-Darwin-arm64-nvv/t1.runtime results.csv
   