#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/itac/t1/2024_10_17_14_37_12-Darwin-arm64-itac/t1.result"; export resultFn
testName="itac"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/itac/itac.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/itac/t1/2024_10_17_14_37_12-Darwin-arm64-itac/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/itac/t1/2024_10_17_14_37_12-Darwin-arm64-itac/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/itac/t1/2024_10_17_14_37_12-Darwin-arm64-itac/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/itac"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/itac/t1/2024_10_17_14_37_12-Darwin-arm64-itac"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     numStep=0
     COUNT=0
     ORIG_HOME=`(cd $HOME; /bin/pwd)`
     HOME=`/bin/pwd`
     cacheDir=`userCacheDir`


     remove_generated_lmod_files mf

     mkdir mf
     (cd /Users/mcawood/Lmod/Lmod/rt/itac/mf; tar cf - . | (cd /Users/mcawood/Lmod/Lmod/rt/itac/t1/2024_10_17_14_37_12-Darwin-arm64-itac/mf; tar xpf - ))
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/itac/t1/2024_10_17_14_37_12-Darwin-arm64-itac/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core


     runLmod --version               # 1
     runLmod load intel mv2          # 2
     mkdir -p .cache/lmod
     buildSpiderT $MODULEPATH > $cacheDir/spiderT.lua
     mkdir mf/Core/itac
     cp /Users/mcawood/Lmod/Lmod/rt/itac/ITAC-1.0.lua mf/Core/itac/1.0.lua
     runLmod --ignore_cache avail    # 3
     runLmod avail                   # 4
     runLmod show itac               # 5
     runLmod load itac               # 6
     runLmod unload mv2              # 7
     runLmod list                    # 8

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/itac/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/itac/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/itac/t1/2024_10_17_14_37_12-Darwin-arm64-itac/t1.result -t /Users/mcawood/Lmod/Lmod/rt/itac/t1/2024_10_17_14_37_12-Darwin-arm64-itac/t1.runtime results.csv
   