#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/build_cache/t1/2024_11_07_13_03_06-Darwin-arm64-build_cache/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/build_cache/t1/2024_11_07_13_03_06-Darwin-arm64-build_cache/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/build_cache"; export testDir
testName="build_cache"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/build_cache/t1/2024_11_07_13_03_06-Darwin-arm64-build_cache/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/build_cache/build_cache.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/build_cache/t1/2024_11_07_13_03_06-Darwin-arm64-build_cache"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/build_cache/t1/2024_11_07_13_03_06-Darwin-arm64-build_cache/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/build_cache/mf
     export MODULEPATH=$MODULEPATH_ROOT/Common

     remove_generated_lmod_files fn broken_mf

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     cat > fn << EOF
/Users/mcawood/Lmod/Lmod/rt/build_cache/t1/2024_11_07_13_03_06-Darwin-arm64-build_cache/cacheDir: /Users/mcawood/Lmod/Lmod/rt/build_cache/t1/2024_11_07_13_03_06-Darwin-arm64-build_cache/last_update
EOF

     lua /Users/mcawood/Lmod/Lmod/src/spiderCacheSupport.in.lua --descriptFn fn >> .lmodrc.lua
     mkdir cacheDir
     
     mkdir -p broken_mf/test
     cp /Users/mcawood/Lmod/Lmod/rt/build_cache/bad_module.lua broken_mf/test/1.0.lua

     runLmod --version                     # 1
     touch last_update
     buildSpiderT $MODULEPATH > cacheDir/spiderT.lua
     runLmod spider                        # 2
     runLmod use broken_mf                 # 3
     runLmod spider                        # 4
     runLmod avail                         # 5
     
     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/build_cache/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/build_cache/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/build_cache/t1/2024_11_07_13_03_06-Darwin-arm64-build_cache/t1.result -t /Users/mcawood/Lmod/Lmod/rt/build_cache/t1/2024_11_07_13_03_06-Darwin-arm64-build_cache/t1.runtime results.csv
   