#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/cnflt_except/t1/2024_11_07_13_03_06-Darwin-arm64-cnflt_except/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/cnflt_except/t1/2024_11_07_13_03_06-Darwin-arm64-cnflt_except/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/cnflt_except"; export testDir
testName="cnflt_except"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/cnflt_except/t1/2024_11_07_13_03_06-Darwin-arm64-cnflt_except/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/cnflt_except/cnflt_except.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/cnflt_except/t1/2024_11_07_13_03_06-Darwin-arm64-cnflt_except"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/cnflt_except/t1/2024_11_07_13_03_06-Darwin-arm64-cnflt_except/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/cnflt_except/mf;     
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/cnflt_except/mf/Core;     
     export LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/cnflt_except

     remove_generated_lmod_files

     runLmod --version                     # 1
     runLmod load B C                      # 2                        
     runLmod load A                        # 3
     runLmod purge                         # 4
     runLmod load B                        # 5
     runLmod load A                        # 6
     runLmod purge                         # 7
     runLmod load miniconda                # 8
     runLmod load A                        # 9

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/cnflt_except/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/cnflt_except/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/cnflt_except/t1/2024_11_07_13_03_06-Darwin-arm64-cnflt_except/t1.result -t /Users/mcawood/Lmod/Lmod/rt/cnflt_except/t1/2024_11_07_13_03_06-Darwin-arm64-cnflt_except/t1.runtime results.csv
   