#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/family/t1/2024_10_17_14_37_12-Darwin-arm64-family/t1.result"; export resultFn
testName="family"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/family/family.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/family/t1/2024_10_17_14_37_12-Darwin-arm64-family/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/family/t1/2024_10_17_14_37_12-Darwin-arm64-family/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/family/t1/2024_10_17_14_37_12-Darwin-arm64-family/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/family"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/family/t1/2024_10_17_14_37_12-Darwin-arm64-family"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/family/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core

     remove_generated_lmod_files

     runLmod --version                         # 1
     runLmod -T load ibmA openmpi phdf5        # 2
     runLmod list                              # 3
     runLmod -T load gccA                      # 4
     runLmod avail                             # 5
     runLmod -T load ibmA                      # 6
####################################
# Test for bad family name
     runLmod load tcc                          # 7

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/family/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/family/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/family/t1/2024_10_17_14_37_12-Darwin-arm64-family/t1.result -t /Users/mcawood/Lmod/Lmod/rt/family/t1/2024_10_17_14_37_12-Darwin-arm64-family/t1.runtime results.csv
   