#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/use_unuse"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/use_unuse/t1/2024_11_06_15_50_29-Darwin-arm64-use_unuse/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/use_unuse/use_unuse.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/use_unuse/t1/2024_11_06_15_50_29-Darwin-arm64-use_unuse/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/use_unuse/t1/2024_11_06_15_50_29-Darwin-arm64-use_unuse/t1.result"; export resultFn
testName="use_unuse"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/use_unuse/t1/2024_11_06_15_50_29-Darwin-arm64-use_unuse"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/use_unuse/t1/2024_11_06_15_50_29-Darwin-arm64-use_unuse/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/use_unuse/mf/Core;     export MODULEPATH
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/use_unuse/mf;     export MODULEPATH_ROOT
     
     remove_generated_lmod_files

     runLmod --version                   # 1
     runLmod load a                      # 2
     runLmod unuse /Users/mcawood/Lmod/Lmod/rt/use_unuse/mf/Core    # 3

     runLmod use   /Users/mcawood/Lmod/Lmod/rt/use_unuse/mf/RTM     # 4
     runLmod unuse /Users/mcawood/Lmod/Lmod/rt/use_unuse/mf/RTM     # 5

     runLmod use   ../../mf/RTM          # 6

     unsetMT
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/use_unuse/mf/RTM
     runLmod unuse /Users/mcawood/Lmod/Lmod/rt/use_unuse/mf/RTM     # 7

     unsetMT
     runLmod use   /Users/mcawood/Lmod/Lmod/rt/use_unuse/mf/RTM2    # 8
     runLmod unuse /Users/mcawood/Lmod/Lmod/rt/use_unuse/mf/RTM2    # 9
     runLmod use   --help                #10
     runLmod use   -h                    #11

     HOME=$ORIG_HOME


     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/use_unuse/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/use_unuse/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/use_unuse/t1/2024_11_06_15_50_29-Darwin-arm64-use_unuse/t1.result -t /Users/mcawood/Lmod/Lmod/rt/use_unuse/t1/2024_11_06_15_50_29-Darwin-arm64-use_unuse/t1.runtime results.csv
   