#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/tacc/t1/2024_10_17_14_37_12-Darwin-arm64-tacc/t1.result"; export resultFn
testName="tacc"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/tacc/tacc.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/tacc/t1/2024_10_17_14_37_12-Darwin-arm64-tacc/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/tacc/t1/2024_10_17_14_37_12-Darwin-arm64-tacc/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/tacc/t1/2024_10_17_14_37_12-Darwin-arm64-tacc/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/tacc"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/tacc/t1/2024_10_17_14_37_12-Darwin-arm64-tacc"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     ORIGPATH=$PATH
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/tacc/mf;     export MODULEPATH_ROOT
     MODULEPATH=$MODULEPATH_ROOT/TACC;  export MODULEPATH

     remove_generated_lmod_files

     runLmod --version              # 1
     runLmod avail                  # 2
     runLmod load TACC              # 3
     runLmod help mvapich1          # 4
     runLmod list                   # 5
     runLmod --brief list           # 6 
     runLmod --latest load pgi      # 7
     runLmod list                   # 8
     runLmod load pgi               # 9
     runLmod list                   #10
     runLmod --latest swap pgi pgi  #11
     runLmod list                   #12
     runLmod unload cluster         #13
     runLmod purge                  #14
     runLmod use /Users/mcawood/Lmod/Lmod/rt/tacc/mf/Base #15
     runLmod show gatk              #16
     runLmod load gatk              #17
     runLmod unload gatk            #18
     runLmod load stir              #19
     runLmod load foo               #20
     runLmod load empty_unload      #21



     PATH=$ORIGPATH
     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/tacc/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/tacc/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/tacc/t1/2024_10_17_14_37_12-Darwin-arm64-tacc/t1.result -t /Users/mcawood/Lmod/Lmod/rt/tacc/t1/2024_10_17_14_37_12-Darwin-arm64-tacc/t1.runtime results.csv
   