#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/keyword"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/keyword/t1/2024_11_06_15_50_29-Darwin-arm64-keyword/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/keyword/keyword.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/keyword/t1/2024_11_06_15_50_29-Darwin-arm64-keyword/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/keyword/t1/2024_11_06_15_50_29-Darwin-arm64-keyword/t1.result"; export resultFn
testName="keyword"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/keyword/t1/2024_11_06_15_50_29-Darwin-arm64-keyword"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/keyword/t1/2024_11_06_15_50_29-Darwin-arm64-keyword/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     LMOD_TERM_WIDTH=150;            export LMOD_TERM_WIDTH
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/keyword/mf;  export MODULEPATH_ROOT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/keyword/mf/Core
     export MODULEPATH
     unset TERM

     rm -f _stderr.* _stdout.* err.* out.* .lmod.d .lmodrc.lua .cache .config
     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     runLmod --version                  # 1
     runLmod           keyword graph    # 2
     runLmod --terse   keyword graph    # 3

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/keyword/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/keyword/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/keyword/t1/2024_11_06_15_50_29-Darwin-arm64-keyword/t1.result -t /Users/mcawood/Lmod/Lmod/rt/keyword/t1/2024_11_06_15_50_29-Darwin-arm64-keyword/t1.runtime results.csv
   