#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/complete"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/complete/t1/2024_11_06_15_50_29-Darwin-arm64-complete/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/complete/complete.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/complete/t1/2024_11_06_15_50_29-Darwin-arm64-complete/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/complete/t1/2024_11_06_15_50_29-Darwin-arm64-complete/t1.result"; export resultFn
testName="complete"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/complete/t1/2024_11_06_15_50_29-Darwin-arm64-complete"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/complete/t1/2024_11_06_15_50_29-Darwin-arm64-complete/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/complete/mf

     remove_generated_lmod_files

     runLmod --version                         # 1
     runLmod load   spack                      # 2
     runLmod unload spack                      # 3
     runLmod load   broken_complete            # 4
     runLmod load   tcl_spack                  # 5
     runLmod unload tcl_spack                  # 6
     runLmod show   spack                      # 7
     runLmod show   tcl_spack                  # 8
     runLmod load   foo/1.0                    # 9

     


     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/complete/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/complete/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/complete/t1/2024_11_06_15_50_29-Darwin-arm64-complete/t1.result -t /Users/mcawood/Lmod/Lmod/rt/complete/t1/2024_11_06_15_50_29-Darwin-arm64-complete/t1.runtime results.csv
   