#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/eb"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/eb/t1/2024_11_06_15_50_29-Darwin-arm64-eb/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/eb/eb.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/eb/t1/2024_11_06_15_50_29-Darwin-arm64-eb/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/eb/t1/2024_11_06_15_50_29-Darwin-arm64-eb/t1.result"; export resultFn
testName="eb"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/eb/t1/2024_11_06_15_50_29-Darwin-arm64-eb"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/eb/t1/2024_11_06_15_50_29-Darwin-arm64-eb/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/eb/mf;       export MODULEPATH

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     mkdir -p $HOME/.cache/lmod

     buildSpiderT $MODULEPATH > $HOME/.cache/lmod/spiderT.lua
     runLmod --version                  # 1
     runLmod load numpy                 # 2
     runLmod list                       # 3
     runLmod load CMake bam2fastq       # 4
     runLmod list                       # 5

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/eb/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/eb/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/eb/t1/2024_11_06_15_50_29-Darwin-arm64-eb/t1.result -t /Users/mcawood/Lmod/Lmod/rt/eb/t1/2024_11_06_15_50_29-Darwin-arm64-eb/t1.runtime results.csv
   