#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/tamu"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/tamu/t1/2024_11_06_15_50_29-Darwin-arm64-tamu/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/tamu/tamu.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/tamu/t1/2024_11_06_15_50_29-Darwin-arm64-tamu/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/tamu/t1/2024_11_06_15_50_29-Darwin-arm64-tamu/t1.result"; export resultFn
testName="tamu"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/tamu/t1/2024_11_06_15_50_29-Darwin-arm64-tamu"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/tamu/t1/2024_11_06_15_50_29-Darwin-arm64-tamu/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/tamu/mf;    export MODULEPATH_ROOT
     LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/tamu;     export LMOD_PACKAGE_PATH
     MODULEPATH=$MODULEPATH_ROOT/Core; export MODULEPATH

     remove_generated_lmod_files

     runLmod --version              # 1
     runLmod spider                 # 2
     runLmod load ucc/9.0           # 3
     runLmod avail                  # 4
     runLmod load umpi              # 5
     runLmod avail                  # 6
     runLmod load uapp              # 7
     runLmod avail                  # 8
     runLmod spider uapp            # 9
     runLmod spider uapp/7.0.8.1    #10



     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/tamu/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/tamu/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/tamu/t1/2024_11_06_15_50_29-Darwin-arm64-tamu/t1.result -t /Users/mcawood/Lmod/Lmod/rt/tamu/t1/2024_11_06_15_50_29-Darwin-arm64-tamu/t1.runtime results.csv
   