#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/refresh/t1/2024_11_07_13_03_06-Darwin-arm64-refresh/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/refresh/t1/2024_11_07_13_03_06-Darwin-arm64-refresh/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/refresh"; export testDir
testName="refresh"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/refresh/t1/2024_11_07_13_03_06-Darwin-arm64-refresh/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/refresh/refresh.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/refresh/t1/2024_11_07_13_03_06-Darwin-arm64-refresh"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/refresh/t1/2024_11_07_13_03_06-Darwin-arm64-refresh/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/refresh/mf;      export MODULEPATH_ROOT
     MODULEPATH=$MODULEPATH_ROOT/Core;   export MODULEPATH

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     mkdir -p $HOME/.cache/lmod

     runLmod --version                  # 1
     runLmod load a b c                 # 2
     runLmod refresh                    # 3
     runLmod purge                      # 4
     runLmod load marco/1.0             # 5
     runLmod refresh                    # 6



     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/refresh/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/refresh/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/refresh/t1/2024_11_07_13_03_06-Darwin-arm64-refresh/t1.result -t /Users/mcawood/Lmod/Lmod/rt/refresh/t1/2024_11_07_13_03_06-Darwin-arm64-refresh/t1.runtime results.csv
   