#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/changeMPATH"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/changeMPATH/t1/2024_11_06_15_50_29-Darwin-arm64-changeMPATH/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/changeMPATH/changeMPATH.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/changeMPATH/t1/2024_11_06_15_50_29-Darwin-arm64-changeMPATH/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/changeMPATH/t1/2024_11_06_15_50_29-Darwin-arm64-changeMPATH/t1.result"; export resultFn
testName="changeMPATH"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/changeMPATH/t1/2024_11_06_15_50_29-Darwin-arm64-changeMPATH"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/changeMPATH/t1/2024_11_06_15_50_29-Darwin-arm64-changeMPATH/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/changeMPATH/mf;      export MODULEPATH_ROOT
     MODULEPATH="$MODULEPATH_ROOT/Core"; export MODULEPATH

     rm -rf _stderr.* _stdout.* err.* out.* .lmod.d .lmodrc.lua .cache .config
     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     runLmod --version                        # 1
     runLmod load admin PrgEnv                # 2
     runLmod save default                     # 3

     runLmod purge                            # 4
     unsetMT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/changeMPATH/mf/Core2:/Users/mcawood/Lmod/Lmod/rt/changeMPATH/mf/Core

     runLmod restore                          # 5

     runLmod purge                            # 6
     unsetMT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/changeMPATH/mf/Core

     runLmod use  /Users/mcawood/Lmod/Lmod/rt/changeMPATH/mf/Core2         # 7
     runLmod load admin PrgEnv                # 8
     runLmod list                             # 9
     runLmod save default                     #10

     runLmod purge                            #11
     unsetMT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/changeMPATH/mf/Core

     runLmod restore                          #12
     runLmod list                             #13
     runLmod save foo                         #14

     export LMOD_SYSTEM_DEFAULT_MODULES=__NO_SYSTEM_DEFAULT_MODULES__
     runLmod reset                            #15

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/changeMPATH/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/changeMPATH/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/changeMPATH/t1/2024_11_06_15_50_29-Darwin-arm64-changeMPATH/t1.result -t /Users/mcawood/Lmod/Lmod/rt/changeMPATH/t1/2024_11_06_15_50_29-Darwin-arm64-changeMPATH/t1.runtime results.csv
   