#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/ugent_startup"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_11_06_15_50_29-Darwin-arm64-ugent_startup/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/ugent_startup.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_11_06_15_50_29-Darwin-arm64-ugent_startup/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_11_06_15_50_29-Darwin-arm64-ugent_startup/t1.result"; export resultFn
testName="ugent_startup"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_11_06_15_50_29-Darwin-arm64-ugent_startup"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_11_06_15_50_29-Darwin-arm64-ugent_startup/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/ugent_startup/mf/Core

     remove_generated_lmod_files

     export VSC_DEFAULT_CLUSTER_MODULE=delcatty

     runLmod --version                         # 1
     runLmod avail                             # 2
     runLmod --show_hidden avail               # 3
     runLmod load cluster                      # 4
     runLmod list                              # 5

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/ugent_startup/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/ugent_startup/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_11_06_15_50_29-Darwin-arm64-ugent_startup/t1.result -t /Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_11_06_15_50_29-Darwin-arm64-ugent_startup/t1.runtime results.csv
   