#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/jsonShell/t1/2024_11_07_13_03_06-Darwin-arm64-jsonShell/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/jsonShell/t1/2024_11_07_13_03_06-Darwin-arm64-jsonShell/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/jsonShell"; export testDir
testName="jsonShell"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/jsonShell/t1/2024_11_07_13_03_06-Darwin-arm64-jsonShell/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/jsonShell/jsonShell.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/jsonShell/t1/2024_11_07_13_03_06-Darwin-arm64-jsonShell"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/jsonShell/t1/2024_11_07_13_03_06-Darwin-arm64-jsonShell/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/jsonShell/mf/Core;     export MODULEPATH

     remove_generated_lmod_files load.json

     runLmod --version                                             # 1
     LD_PRELOAD= $LUA_EXEC $projectDir/src/lmod.in.lua json load A > load.json
     runBase $LUA_EXEC $projectDir/proj_mgmt/jsonLoadConversion load.json

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/jsonShell/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/jsonShell/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/jsonShell/t1/2024_11_07_13_03_06-Darwin-arm64-jsonShell/t1.result -t /Users/mcawood/Lmod/Lmod/rt/jsonShell/t1/2024_11_07_13_03_06-Darwin-arm64-jsonShell/t1.runtime results.csv
   