#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_10_17_14_37_12-Darwin-arm64-ugent_startup/t1.result"; export resultFn
testName="ugent_startup"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/ugent_startup.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_10_17_14_37_12-Darwin-arm64-ugent_startup/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_10_17_14_37_12-Darwin-arm64-ugent_startup/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_10_17_14_37_12-Darwin-arm64-ugent_startup/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/ugent_startup"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_10_17_14_37_12-Darwin-arm64-ugent_startup"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/ugent_startup/mf/Core

     remove_generated_lmod_files

     export VSC_DEFAULT_CLUSTER_MODULE=delcatty

     runLmod --version                         # 1
     runLmod avail                             # 2
     runLmod --show_hidden avail               # 3
     runLmod load cluster                      # 4
     runLmod list                              # 5

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/ugent_startup/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/ugent_startup/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_10_17_14_37_12-Darwin-arm64-ugent_startup/t1.result -t /Users/mcawood/Lmod/Lmod/rt/ugent_startup/t1/2024_10_17_14_37_12-Darwin-arm64-ugent_startup/t1.runtime results.csv
   