#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/defaults"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/defaults/t1/2024_11_06_15_50_29-Darwin-arm64-defaults/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/defaults/defaults.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/defaults/t1/2024_11_06_15_50_29-Darwin-arm64-defaults/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/defaults/t1/2024_11_06_15_50_29-Darwin-arm64-defaults/t1.result"; export resultFn
testName="defaults"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/defaults/t1/2024_11_06_15_50_29-Darwin-arm64-defaults"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/defaults/t1/2024_11_06_15_50_29-Darwin-arm64-defaults/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/defaults/mf;    export MODULEPATH_ROOT
     MODULEPATH=$MODULEPATH_ROOT/Core; export MODULEPATH
     numStep=0
     COUNT=0
     ORIG_HOME=`(cd $HOME; /bin/pwd)`
     HOME=`/bin/pwd`


     remove_generated_lmod_files

     runLmod --version               # 1
     runLmod avail                   # 2
     runLmod -t -d avail             # 3
     runLmod load a b boost mv2      # 4
     runLmod list                    # 5

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/defaults/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/defaults/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/defaults/t1/2024_11_06_15_50_29-Darwin-arm64-defaults/t1.result -t /Users/mcawood/Lmod/Lmod/rt/defaults/t1/2024_11_06_15_50_29-Darwin-arm64-defaults/t1.runtime results.csv
   