#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/show/t1/2024_10_17_14_37_12-Darwin-arm64-show/t1.result"; export resultFn
testName="show"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/show/show.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/show/t1/2024_10_17_14_37_12-Darwin-arm64-show/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/show/t1/2024_10_17_14_37_12-Darwin-arm64-show/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/show/t1/2024_10_17_14_37_12-Darwin-arm64-show/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/show"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/show/t1/2024_10_17_14_37_12-Darwin-arm64-show"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh
     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/show/mf;  export MODULEPATH_ROOT
     MODULEPATH=$MODULEPATH_ROOT/Core #:$MODULEPATH_ROOT/Compiler/intel/10.1;
     export MODULEPATH

     remove_generated_lmod_files

     runLmod --version               # 1
     runLmod show gcc                # 2
     runLmod show alex               # 3
     runLmod avail                   # 4
     runLmod show boost              # 5
     runLmod load boost/1.47.1       # 6
     runLmod list                    # 7
     runLmod show boost              # 8
     runLmod show boost/1.49.0       # 9
     runLmod use /Users/mcawood/Lmod/Lmod/rt/show/mf/Core2 #10
     runLmod show a                  #11
     runLmod show b_tcl              #12
     runLmod show nosuchmodule       #13
     runLmod --location show a       #14
     runLmod --terse    show a       #15
     runLmod show showMe             #16

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/show/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/show/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/show/t1/2024_10_17_14_37_12-Darwin-arm64-show/t1.result -t /Users/mcawood/Lmod/Lmod/rt/show/t1/2024_10_17_14_37_12-Darwin-arm64-show/t1.runtime results.csv
   