#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/symlink"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/symlink/t1/2024_11_06_15_50_29-Darwin-arm64-symlink/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/symlink/symlink.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/symlink/t1/2024_11_06_15_50_29-Darwin-arm64-symlink/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/symlink/t1/2024_11_06_15_50_29-Darwin-arm64-symlink/t1.result"; export resultFn
testName="symlink"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/symlink/t1/2024_11_06_15_50_29-Darwin-arm64-symlink"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/symlink/t1/2024_11_06_15_50_29-Darwin-arm64-symlink/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/symlink/mf;    export MODULEPATH_ROOT
     MODULEPATH=$MODULEPATH_ROOT/Core; export MODULEPATH

     remove_generated_lmod_files
     rm -f  good.text bad1.text bad2.text

     runLmod --version                  # 1
     runLmod       avail                # 2
     runLmod -t -d avail                # 3
     runLmod load intel a b boost mv2   # 4
     runLmod list                       # 5
     touch   good.text
     ln -s bad bad1.text
     ln -s bad1.text bad2.text
     runLmod load bad_symlink           # 6




     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/symlink/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/symlink/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/symlink/t1/2024_11_06_15_50_29-Darwin-arm64-symlink/t1.result -t /Users/mcawood/Lmod/Lmod/rt/symlink/t1/2024_11_06_15_50_29-Darwin-arm64-symlink/t1.runtime results.csv
   