#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/softwarePage/t1/2024_11_07_13_03_06-Darwin-arm64-softwarePage/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/softwarePage/t1/2024_11_07_13_03_06-Darwin-arm64-softwarePage/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/softwarePage"; export testDir
testName="softwarePage"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/softwarePage/t1/2024_11_07_13_03_06-Darwin-arm64-softwarePage/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/softwarePage/softwarePage.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/softwarePage/t1/2024_11_07_13_03_06-Darwin-arm64-softwarePage"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/softwarePage/t1/2024_11_07_13_03_06-Darwin-arm64-softwarePage/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/softwarePage/mf
     export MODULERCFILE=/Users/mcawood/Lmod/Lmod/rt/softwarePage/rc

     remove_generated_lmod_files

     runLmod --version                                   # 1
     runLmod avail                                       # 2
     runBase runSpiderCmd -o spiderT         $MODULEPATH # 3
     runBase runSpiderCmd -o dbT             $MODULEPATH # 4
     runBase runSpiderCmd -o softwarePageLua $MODULEPATH # 5

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/softwarePage/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/softwarePage/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/softwarePage/t1/2024_11_07_13_03_06-Darwin-arm64-softwarePage/t1.result -t /Users/mcawood/Lmod/Lmod/rt/softwarePage/t1/2024_11_07_13_03_06-Darwin-arm64-softwarePage/t1.runtime results.csv
   