#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/petsc/t1/2024_10_17_14_37_12-Darwin-arm64-petsc/t1.result"; export resultFn
testName="petsc"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/petsc/petsc.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/petsc/t1/2024_10_17_14_37_12-Darwin-arm64-petsc/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/petsc/t1/2024_10_17_14_37_12-Darwin-arm64-petsc/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/petsc/t1/2024_10_17_14_37_12-Darwin-arm64-petsc/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/petsc"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/petsc/t1/2024_10_17_14_37_12-Darwin-arm64-petsc"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/petsc/mf;       export MODULEPATH_ROOT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/petsc/mf/Core;       export MODULEPATH

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     mkdir -p $HOME/.cache/lmod
     buildSpiderT $MODULEPATH > $HOME/.cache/lmod/spiderT.lua

     runLmod --version                  # 1
     runLmod load intel mvapich2        # 2
     runLmod avail                      # 3
     runLmod spider                     # 4
     runLmod spider pet                 # 5

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/petsc/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/petsc/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/petsc/t1/2024_10_17_14_37_12-Darwin-arm64-petsc/t1.result -t /Users/mcawood/Lmod/Lmod/rt/petsc/t1/2024_10_17_14_37_12-Darwin-arm64-petsc/t1.runtime results.csv
   