#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/prophook"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/prophook/t1/2024_11_06_15_50_29-Darwin-arm64-prophook/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/prophook/prophook.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/prophook/t1/2024_11_06_15_50_29-Darwin-arm64-prophook/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/prophook/t1/2024_11_06_15_50_29-Darwin-arm64-prophook/t1.result"; export resultFn
testName="prophook"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/prophook/t1/2024_11_06_15_50_29-Darwin-arm64-prophook"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/prophook/t1/2024_11_06_15_50_29-Darwin-arm64-prophook/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/prophook/mf;
     export LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/prophook

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/rt/prophook/.lmodrc.lua .lmodrc.lua

     runLmod --version                     # 1
     runLmod avail                         # 2
     runLmod load gcc                      # 3
     runLmod list                          # 4


     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/prophook/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/prophook/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/prophook/t1/2024_11_06_15_50_29-Darwin-arm64-prophook/t1.result -t /Users/mcawood/Lmod/Lmod/rt/prophook/t1/2024_11_06_15_50_29-Darwin-arm64-prophook/t1.runtime results.csv
   