#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/versionTest"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/versionTest/t1/2024_11_06_15_50_29-Darwin-arm64-versionTest/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/versionTest/versionTest.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/versionTest/t1/2024_11_06_15_50_29-Darwin-arm64-versionTest/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/versionTest/t1/2024_11_06_15_50_29-Darwin-arm64-versionTest/t1.result"; export resultFn
testName="versionTest"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/versionTest/t1/2024_11_06_15_50_29-Darwin-arm64-versionTest"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/versionTest/t1/2024_11_06_15_50_29-Darwin-arm64-versionTest/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/versionTest/mf;  export MODULEPATH

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     runLmod --version                                      # 1
     runLmod load a                                         # 2
     runLmod load b                                         # 3
     runLmod load c                                         # 4
     runLmod list                                           # 5

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/versionTest/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/versionTest/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/versionTest/t1/2024_11_06_15_50_29-Darwin-arm64-versionTest/t1.result -t /Users/mcawood/Lmod/Lmod/rt/versionTest/t1/2024_11_06_15_50_29-Darwin-arm64-versionTest/t1.runtime results.csv
   