#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/vasp/t1/2024_10_17_14_37_12-Darwin-arm64-vasp/t1.result"; export resultFn
testName="vasp"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/vasp/vasp.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/vasp/t1/2024_10_17_14_37_12-Darwin-arm64-vasp/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/vasp/t1/2024_10_17_14_37_12-Darwin-arm64-vasp/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/vasp/t1/2024_10_17_14_37_12-Darwin-arm64-vasp/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/vasp"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/vasp/t1/2024_10_17_14_37_12-Darwin-arm64-vasp"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/mf;  export MODULEPATH_ROOT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/mf/Core:/Users/mcawood/Lmod/Lmod/mf/Compiler/intel/10.1:/Users/mcawood/Lmod/Lmod/mf/MPI/intel/10.1/openmpi/1.2.6;
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/vasp/mf:$MODULEPATH
     export MODULEPATH

     remove_generated_lmod_files

     runLmod --version                        # 1
     runLmod keyword graph                    # 2
     runLmod whatis vasp                      # 3
     runLmod help vasp                        # 4
     runLmod load vasp                        # 5
     runBase lua /Users/mcawood/Lmod/Lmod/src/spider.in.lua -o list $LMOD_DEFAULT_MODULEPATH  # 6

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     joinBase64Results  -bash  _stderr.orig _stderr.new
     cleanUp _stderr.new err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/vasp/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/vasp/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/vasp/t1/2024_10_17_14_37_12-Darwin-arm64-vasp/t1.result -t /Users/mcawood/Lmod/Lmod/rt/vasp/t1/2024_10_17_14_37_12-Darwin-arm64-vasp/t1.runtime results.csv
   