#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/ref_count"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/ref_count/t1/2024_11_06_15_50_29-Darwin-arm64-ref_count/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/ref_count/ref_count.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/ref_count/t1/2024_11_06_15_50_29-Darwin-arm64-ref_count/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/ref_count/t1/2024_11_06_15_50_29-Darwin-arm64-ref_count/t1.result"; export resultFn
testName="ref_count"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/ref_count/t1/2024_11_06_15_50_29-Darwin-arm64-ref_count"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/ref_count/t1/2024_11_06_15_50_29-Darwin-arm64-ref_count/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/ref_count/mf2

     remove_generated_lmod_files

     export RTM_PATH=/usr/local/mybin:/mybin:/usr/local/mybin:/mybin

     runLmod --version                         # 1

     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/ref_count/mf2
     export NODE_TYPE=cpu
     runLmod load   abc                        # 2
     runLmod list                              # 3
     runLmod unload abc                        # 4

     unsetMT
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/ref_count/mf/Core
     runLmod load rtm                          # 5
     runLmod unload rtm                        # 6


     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/ref_count/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/ref_count/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/ref_count/t1/2024_11_06_15_50_29-Darwin-arm64-ref_count/t1.result -t /Users/mcawood/Lmod/Lmod/rt/ref_count/t1/2024_11_06_15_50_29-Darwin-arm64-ref_count/t1.runtime results.csv
   