#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/checkSyntax/t1/2024_10_17_14_37_12-Darwin-arm64-checkSyntax/t1.result"; export resultFn
testName="checkSyntax"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/checkSyntax/checkSyntax.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/checkSyntax/t1/2024_10_17_14_37_12-Darwin-arm64-checkSyntax/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/checkSyntax/t1/2024_10_17_14_37_12-Darwin-arm64-checkSyntax/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/checkSyntax/t1/2024_10_17_14_37_12-Darwin-arm64-checkSyntax/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/checkSyntax"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/checkSyntax/t1/2024_10_17_14_37_12-Darwin-arm64-checkSyntax"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/checkSyntax/mf; export MODULEPATH

     remove_generated_lmod_files

     runLmod --version                # 1
     runLmod --checkSyntax load 3.7   # 2
     runLmod --checkSyntax load 3.8   # 3
     

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/checkSyntax/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/checkSyntax/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/checkSyntax/t1/2024_10_17_14_37_12-Darwin-arm64-checkSyntax/t1.result -t /Users/mcawood/Lmod/Lmod/rt/checkSyntax/t1/2024_10_17_14_37_12-Darwin-arm64-checkSyntax/t1.runtime results.csv
   