#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/uitSitePkg/t1/2024_11_07_13_03_06-Darwin-arm64-uitSitePkg/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/uitSitePkg/t1/2024_11_07_13_03_06-Darwin-arm64-uitSitePkg/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/uitSitePkg"; export testDir
testName="uitSitePkg"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/uitSitePkg/t1/2024_11_07_13_03_06-Darwin-arm64-uitSitePkg/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/uitSitePkg/uitSitePkg.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/uitSitePkg/t1/2024_11_07_13_03_06-Darwin-arm64-uitSitePkg"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/uitSitePkg/t1/2024_11_07_13_03_06-Darwin-arm64-uitSitePkg/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/uitSitePkg/mf;     
     export MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/uitSitePkg/mf/Core;     
     export LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/uitSitePkg/mf/site-scripts; 


     remove_generated_lmod_files

     runLmod --version               # 1
     runLmod load gcc python         # 2
     runLmod list                    # 3
     runLmod save default            # 4
     runLmod restore                 # 5
     runLmod spider                  # 6
     runLmod spider python           # 7

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv

     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/uitSitePkg/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/uitSitePkg/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/uitSitePkg/t1/2024_11_07_13_03_06-Darwin-arm64-uitSitePkg/t1.result -t /Users/mcawood/Lmod/Lmod/rt/uitSitePkg/t1/2024_11_07_13_03_06-Darwin-arm64-uitSitePkg/t1.runtime results.csv
   