#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/perl/t1/2024_10_17_14_37_12-Darwin-arm64-perl/t1.result"; export resultFn
testName="perl"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/perl/perl.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/perl/t1/2024_10_17_14_37_12-Darwin-arm64-perl/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/perl/t1/2024_10_17_14_37_12-Darwin-arm64-perl/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/perl/t1/2024_10_17_14_37_12-Darwin-arm64-perl/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/perl"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/perl/t1/2024_10_17_14_37_12-Darwin-arm64-perl"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/perl/mf;     export MODULEPATH_ROOT
     MODULEPATH="/Users/mcawood/Lmod/Lmod/rt/perl/mf/Core";   export MODULEPATH

     remove_generated_lmod_files init

     mkdir init
     sed -e 's|@PKG@/libexec/lmod|lua /Users/mcawood/Lmod/Lmod/src/lmod.in.lua|g' \
              < /Users/mcawood/Lmod/Lmod/init/perl > init/perl

cat > perl.pl << EOF
#!/usr/bin/env perl
use strict;

require "/Users/mcawood/Lmod/Lmod/rt/perl/t1/2024_10_17_14_37_12-Darwin-arm64-perl/init/perl";

module("load foobar");

print "\\\$ENV{FOOBAR}: ".\$ENV{"FOOBAR"}."\n";

print STDERR "\navail:\n";
module("avail");
print STDERR "\nlist\n";
module("list");
print  STDERR "\nunload foobar\n";
module("unload foobar");
print  STDERR "\nlist\n";
module("list");
print "\\\$ENV{FOOBAR}: ".\$ENV{"FOOBAR"}."\n";
EOF




     chmod +x perl.pl
     ./perl.pl  > _stdout.000 2> _stderr.000

     HOME=$ORIG_HOME
     cleanUp _stdout.000 out.txt
     cleanUp _stderr.000 err.txt
     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/perl/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/perl/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/perl/t1/2024_10_17_14_37_12-Darwin-arm64-perl/t1.result -t /Users/mcawood/Lmod/Lmod/rt/perl/t1/2024_10_17_14_37_12-Darwin-arm64-perl/t1.runtime results.csv
   