#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/priority"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/priority/t1/2024_11_06_15_50_29-Darwin-arm64-priority/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/priority/priority.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/priority/t1/2024_11_06_15_50_29-Darwin-arm64-priority/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/priority/t1/2024_11_06_15_50_29-Darwin-arm64-priority/t1.result"; export resultFn
testName="priority"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/priority/t1/2024_11_06_15_50_29-Darwin-arm64-priority"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/priority/t1/2024_11_06_15_50_29-Darwin-arm64-priority/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/priority/mf;  export MODULEPATH_ROOT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/priority/mf/Core;  export MODULEPATH

     remove_generated_lmod_files

     runLmod --version                            # 1
     runLmod use --priority 100 /Users/mcawood/Lmod/Lmod/rt/priority/mf/RTM # 2
     runLmod use --priority 100 /Users/mcawood/Lmod/Lmod/rt/priority/mf/RTM # 3
     runLmod load priority                        # 4
     runLmod load a                               # 5
     runLmod load tdog                            # 6
     runLmod list                                 # 7
     runLmod unload priority                      # 8
     runLmod list                                 # 9
     runLmod show tdog                            #10

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/priority/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/priority/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/priority/t1/2024_11_06_15_50_29-Darwin-arm64-priority/t1.result -t /Users/mcawood/Lmod/Lmod/rt/priority/t1/2024_11_06_15_50_29-Darwin-arm64-priority/t1.runtime results.csv
   