#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/nil/t1/2024_10_17_14_37_12-Darwin-arm64-nil/t1.result"; export resultFn
testName="nil"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/nil/nil.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/nil/t1/2024_10_17_14_37_12-Darwin-arm64-nil/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/nil/t1/2024_10_17_14_37_12-Darwin-arm64-nil/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/nil/t1/2024_10_17_14_37_12-Darwin-arm64-nil/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/nil"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/nil/t1/2024_10_17_14_37_12-Darwin-arm64-nil"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     LMOD_TERM_WIDTH=80;             export LMOD_TERM_WIDTH
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/nil/mf;  export MODULEPATH_ROOT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/nil/mf/Core;  export MODULEPATH

     remove_generated_lmod_files

     runLmod --version  # 1
     runLmod spider     # 2

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     HOME=$ORIG_HOME

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/nil/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/nil/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/nil/t1/2024_10_17_14_37_12-Darwin-arm64-nil/t1.result -t /Users/mcawood/Lmod/Lmod/rt/nil/t1/2024_10_17_14_37_12-Darwin-arm64-nil/t1.runtime results.csv
   