#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/ifur/t1/2024_11_07_13_03_06-Darwin-arm64-ifur/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/ifur/t1/2024_11_07_13_03_06-Darwin-arm64-ifur/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/ifur"; export testDir
testName="ifur"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/ifur/t1/2024_11_07_13_03_06-Darwin-arm64-ifur/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/ifur/ifur.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/ifur/t1/2024_11_07_13_03_06-Darwin-arm64-ifur"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/ifur/t1/2024_11_07_13_03_06-Darwin-arm64-ifur/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/ifur/mf
     export MODULEPATH=$MODULEPATH_ROOT/core

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     runLmod --version                # 1
     runLmod load stdenv              # 2
     runLmod avail                    # 3
     runLmod load GCC                 # 4
     runLmod avail                    # 5
     runLmod load OpenMPI             # 6
     runLmod load Python              # 7
     runLmod list                     # 8
     runLmod unload Python            # 9
     runLmod list                     #10


     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/ifur/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/ifur/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/ifur/t1/2024_11_07_13_03_06-Darwin-arm64-ifur/t1.result -t /Users/mcawood/Lmod/Lmod/rt/ifur/t1/2024_11_07_13_03_06-Darwin-arm64-ifur/t1.runtime results.csv
   