#!/bin/bash
# -*- shell-script -*-

packageName="rt"; export packageName
idTag="t1"; export idTag
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/unload/t1/2024_11_07_13_08_25-Darwin-arm64-unload/t1.runtime"; export runtimeFn
tag="2024_11_07"; export tag
outputDir="/Users/mcawood/Lmod/Lmod/rt/unload/t1/2024_11_07_13_08_25-Darwin-arm64-unload"; export outputDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/unload/t1/2024_11_07_13_08_25-Darwin-arm64-unload/message.lua"; export messageFn
testName="unload"; export testName
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/unload/unload.tdesc"; export testdescriptFn
target=""; export target
testDir="/Users/mcawood/Lmod/Lmod/rt/unload"; export testDir
TARGET=""; export TARGET
resultFn="/Users/mcawood/Lmod/Lmod/rt/unload/t1/2024_11_07_13_08_25-Darwin-arm64-unload/t1.result"; export resultFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/unload/t1/2024_11_07_13_08_25-Darwin-arm64-unload/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/unload/mf;       export MODULEPATH_ROOT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/unload/mf/Core;       export MODULEPATH

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua

     mkdir -p $HOME/.cache/lmod
     buildSpiderT $MODULEPATH > $HOME/.cache/lmod/spiderT.lua

     runLmod --version                  # 1
     runLmod spider                     # 2
     runLmod load intel                 # 3
     runLmod load mpich2 petsc          # 4
     runLmod avail                      # 5
     runLmod list                       # 6
     runLmod unload intel               # 7
     runLmod load   B                   # 8
     runLmod unload B                   # 9
     runLmod load   C                   # 10
     runLmod -D unload C                   # 11

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/unload/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/unload/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/unload/t1/2024_11_07_13_08_25-Darwin-arm64-unload/t1.result -t /Users/mcawood/Lmod/Lmod/rt/unload/t1/2024_11_07_13_08_25-Darwin-arm64-unload/t1.runtime results.csv
   
