#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/hash_try_load/t1/2024_10_17_14_37_12-Darwin-arm64-hash_try_load/t1.result"; export resultFn
testName="hash_try_load"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/hash_try_load/hash_try_load.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/hash_try_load/t1/2024_10_17_14_37_12-Darwin-arm64-hash_try_load/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/hash_try_load/t1/2024_10_17_14_37_12-Darwin-arm64-hash_try_load/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/hash_try_load/t1/2024_10_17_14_37_12-Darwin-arm64-hash_try_load/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/hash_try_load"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/hash_try_load/t1/2024_10_17_14_37_12-Darwin-arm64-hash_try_load"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/hash_try_load/t1/2024_10_17_14_37_12-Darwin-arm64-hash_try_load/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core

     remove_generated_lmod_files mf/Core

     mkdir -p mf/Core
     cp /Users/mcawood/Lmod/Lmod/rt/hash_try_load/cluster /Users/mcawood/Lmod/Lmod/rt/hash_try_load/TACC mf/Core

     runLmod --version                     # 1
     runLmod load TACC                     # 2
     runLmod save                          # 3
     runLmod purge                         # 4
     unsetMT
     runLmod restore                       # 5
     sed -e "s/##%%##//g" < mf/Core/cluster > mf/Core/cluster.new
     mv mf/Core/cluster.new mf/Core/cluster
     runLmod purge                         # 6
     unsetMT
     runLmod restore                       # 7



     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/hash_try_load/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/hash_try_load/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/hash_try_load/t1/2024_10_17_14_37_12-Darwin-arm64-hash_try_load/t1.result -t /Users/mcawood/Lmod/Lmod/rt/hash_try_load/t1/2024_10_17_14_37_12-Darwin-arm64-hash_try_load/t1.runtime results.csv
   