#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/personal_mf/t1/2024_10_17_14_37_12-Darwin-arm64-personal_mf/t1.result"; export resultFn
testName="personal_mf"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/personal_mf/personal_mf.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/personal_mf/t1/2024_10_17_14_37_12-Darwin-arm64-personal_mf/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/personal_mf/t1/2024_10_17_14_37_12-Darwin-arm64-personal_mf/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/personal_mf/t1/2024_10_17_14_37_12-Darwin-arm64-personal_mf/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/personal_mf"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/personal_mf/t1/2024_10_17_14_37_12-Darwin-arm64-personal_mf"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/rt/personal_mf/.modulerc .

     runLmod --version                                            # 1
     runLmod use /Users/mcawood/Lmod/Lmod/rt/personal_mf/.modulefiles                          # 2
     runLmod load git git-annex htop luajit luarocks hdf5/1.8.15  # 3
     runLmod list                                                 # 4

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/personal_mf/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/personal_mf/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/personal_mf/t1/2024_10_17_14_37_12-Darwin-arm64-personal_mf/t1.result -t /Users/mcawood/Lmod/Lmod/rt/personal_mf/t1/2024_10_17_14_37_12-Darwin-arm64-personal_mf/t1.runtime results.csv
   