#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/colorize/t1/2024_10_17_14_37_12-Darwin-arm64-colorize/t1.result"; export resultFn
testName="colorize"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/colorize/colorize.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/colorize/t1/2024_10_17_14_37_12-Darwin-arm64-colorize/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/colorize/t1/2024_10_17_14_37_12-Darwin-arm64-colorize/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/colorize/t1/2024_10_17_14_37_12-Darwin-arm64-colorize/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/colorize"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/colorize/t1/2024_10_17_14_37_12-Darwin-arm64-colorize"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/colorize/mf;     export MODULEPATH
     export TERM=xterm

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/rt/colorize/.lmodrc.lua .lmodrc.lua

     runLmod --version                  # 1
     export LMOD_COLORIZE=FORCE
     export LMOD_TERM_WIDTH=59
     runLmod avail                      # 2
     export LMOD_TERM_WIDTH=71
     runLmod avail                      # 3
     export LMOD_TERM_WIDTH=76
     runLmod avail                      # 4
     export LMOD_TERM_WIDTH=85
     runLmod avail                      # 5
     export LMOD_TERM_WIDTH=97
     runLmod avail                      # 6
     export LMOD_TERM_WIDTH=108
     runLmod avail                      # 7
     export LMOD_TERM_WIDTH=119
     runLmod avail                      # 8

     HOME=$ORIG_HOME



     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/colorize/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/colorize/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/colorize/t1/2024_10_17_14_37_12-Darwin-arm64-colorize/t1.result -t /Users/mcawood/Lmod/Lmod/rt/colorize/t1/2024_10_17_14_37_12-Darwin-arm64-colorize/t1.runtime results.csv
   