#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/rmap"; export testDir
testName="rmap"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/rmap/rmap.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/rmap/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core
     export APPS_DIR=/Users/mcawood/Lmod/Lmod/rt/rmap/apps
     export MY_BIN=/Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap/my_bin

     remove_generated_lmod_files more_apps otherBin

     mkdir -p more_apps/bin
     cp /Users/mcawood/Lmod/Lmod/rt/rmap/echo_this.sh more_apps/bin
     ln -s more_apps/bin my_bin
    

     runLmod --version                     # 1
     mkdir -p $HOME/.cache/lmod
     runBase buildSpiderT $MODULEPATH      # 2
     runBase buildDbT     $MODULEPATH      # 3
     runBase buildRmapT   $MODULEPATH      # 4
     runLmod spider                        # 5

     unsetMT

     export MODULEPATH=$MODULEPATH_ROOT/2Core
     runLmod spider                        # 6
     runBase buildSpiderT $MODULEPATH      # 7
     runBase buildDbT     $MODULEPATH      # 8

     export MODULEPATH_LOOP=1

     runBase buildSpiderT $MODULEPATH      # 9
     runBase buildDbT     $MODULEPATH      #10

     unset MODULEPATH_LOOP
     mkdir -p /Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap/otherBin
     export OTHERBIN=/Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap/otherBin
     runBase buildRmapT   $MODULEPATH      #11
     export LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/rmap/site;
     runBase buildRmapT   $MODULEPATH      #12



     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/rmap/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/rmap/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap/t1.result -t /Users/mcawood/Lmod/Lmod/rt/rmap/t1/2024_11_07_13_03_06-Darwin-arm64-rmap/t1.runtime results.csv
   