#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/isloaded/t1/2024_11_07_13_03_06-Darwin-arm64-isloaded/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/isloaded/t1/2024_11_07_13_03_06-Darwin-arm64-isloaded/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/isloaded"; export testDir
testName="isloaded"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/isloaded/t1/2024_11_07_13_03_06-Darwin-arm64-isloaded/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/isloaded/isloaded.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/isloaded/t1/2024_11_07_13_03_06-Darwin-arm64-isloaded"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/isloaded/t1/2024_11_07_13_03_06-Darwin-arm64-isloaded/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh
     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/isloaded/mf;     export MODULEPATH_ROOT
     MODULEPATH=$MODULEPATH_ROOT/Core;  export MODULEPATH

     remove_generated_lmod_files

     runLmod --version                # 1
     runLmod load PrgEnv              # 2
     runLmod use  /Users/mcawood/Lmod/Lmod/rt/isloaded/mf/Core2 # 3
     runLmod load foo/1.0             # 4
     runLmod load isloaded            # 5
     runLmod del  isloaded            # 6

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/isloaded/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/isloaded/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/isloaded/t1/2024_11_07_13_03_06-Darwin-arm64-isloaded/t1.result -t /Users/mcawood/Lmod/Lmod/rt/isloaded/t1/2024_11_07_13_03_06-Darwin-arm64-isloaded/t1.runtime results.csv
   