#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/use_append/t1/2024_11_07_13_03_06-Darwin-arm64-use_append/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/use_append/t1/2024_11_07_13_03_06-Darwin-arm64-use_append/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/use_append"; export testDir
testName="use_append"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/use_append/t1/2024_11_07_13_03_06-Darwin-arm64-use_append/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/use_append/use_append.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/use_append/t1/2024_11_07_13_03_06-Darwin-arm64-use_append"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/use_append/t1/2024_11_07_13_03_06-Darwin-arm64-use_append/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh
     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/use_append/mf/Core;     export MODULEPATH
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/use_append/mf;     export MODULEPATH_ROOT

     remove_generated_lmod_files

     runLmod --version      # 1
     runLmod load append    # 2
     runLmod show append    # 3
     runLmod list           # 4

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/use_append/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/use_append/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/use_append/t1/2024_11_07_13_03_06-Darwin-arm64-use_append/t1.result -t /Users/mcawood/Lmod/Lmod/rt/use_append/t1/2024_11_07_13_03_06-Darwin-arm64-use_append/t1.runtime results.csv
   