#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/extensions/t1/2024_10_17_14_37_12-Darwin-arm64-extensions/t1.result"; export resultFn
testName="extensions"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/extensions/extensions.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/extensions/t1/2024_10_17_14_37_12-Darwin-arm64-extensions/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/extensions/t1/2024_10_17_14_37_12-Darwin-arm64-extensions/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/extensions/t1/2024_10_17_14_37_12-Darwin-arm64-extensions/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/extensions"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/extensions/t1/2024_10_17_14_37_12-Darwin-arm64-extensions"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/extensions/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/rt/extensions/dot.modulerc.lua .modulerc.lua

     runLmod --version                         # 1

     mkdir -p .cache/lmod
     buildSpiderT $MODULEPATH > $HOME/.cache/lmod/spiderT.lua
     buildDbT     $MODULEPATH > $HOME/.cache/lmod/dbT.lua

     runLmod avail                             # 2
     runLmod load gcc python                   # 3
     runLmod avail                             # 4
     runLmod --show_hidden avail               # 5
     runLmod load intel python                 # 6
     runLmod avail                             # 7

     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/extensions/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/extensions/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/extensions/t1/2024_10_17_14_37_12-Darwin-arm64-extensions/t1.result -t /Users/mcawood/Lmod/Lmod/rt/extensions/t1/2024_10_17_14_37_12-Darwin-arm64-extensions/t1.runtime results.csv
   