#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/saverestore"; export testDir
testName="saverestore"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/saverestore/saverestore.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/saverestore/TACC;        export MODULEPATH
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/saverestore;        export MODULEPATH_ROOT
     LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/saverestore;      export LMOD_PACKAGE_PATH

     remove_generated_lmod_files Core

     LMOD_PACKAGE_PATH=/Users/mcawood/Lmod/Lmod/rt/saverestore;      export LMOD_PACKAGE_PATH
     runLmod --version               # 1
     runLmod describe                # 2 
     runLmod load TACC               # 3
     runLmod load pgi/7.2-5          # 4
     runLmod list                    # 5
     runLmod save default            # 6
     unset OMP_NUM_THREADS
     runLmod restore                 # 7 
     runLmod list                    # 8
     runLmod use /Users/mcawood/Lmod/Lmod/rt/saverestore/TACC2    # 9
     runLmod load a                  #10
     runLmod list                    #11
     runLmod save                    #12
     runLmod describe                #13

     runLmod purge                   #14
     unsetMT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/saverestore/TACC

     runLmod restore                 #15
     runLmod list                    #16
     runLmod spider                  #17

     runLmod purge                   #18
     unsetMT
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/Core
     mkdir      /Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/Core
     (cd /Users/mcawood/Lmod/Lmod/rt/saverestore/Core; tar cf - . | (cd /Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/Core && tar xBf -))
     sed -e 's|@outputDir@|/Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore|g'  < /Users/mcawood/Lmod/Lmod/rt/saverestore/.lmod.d/stdenv > /Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/.config/lmod/stdenv
     runLmod restore stdenv          #19
     sed -e 's/--#%#//g'  < /Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/Core/StdEnv.lua > /Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/Core/StdEnv.new
     mv /Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/Core/StdEnv.new /Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/Core/StdEnv.lua
     runLmod restore stdenv          #20

     runLmod purge                   #21
     runLmod use /Users/mcawood/Lmod/Lmod/rt/saverestore/PREREQ   #22
     runLmod load M T A              #23
     runLmod list                    #24
     runLmod save                    #25
     runLmod restore                 #26
     runLmod list                    #27
     runLmod purge                   #28
     runLmod load a b                #29
     runLmod save                    #30
     rm Core/a/default
     ln -s 3.0 Core/a/default
     runLmod restore                 #31
     runLmod list                    #32
     export LMOD_PIN_VERSIONS=yes
     runLmod purge                   #33
     runLmod restore                 #34
     runLmod list                    #35

     runLmod purge                   #36
     runLmod use /Users/mcawood/Lmod/Lmod/rt/saverestore/EB       #37
     runLmod load gcc/5.4            #38
     runLmod list                    #39
     runLmod save    foss            #40
     runLmod restore foss            #41
     runLmod list                    #42
     runLmod purge                   #43
     unsetMT

     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/saverestore/Core     
     export LMOD_CACHED_LOADS=yes
     mkdir -p $HOME/.cache/lmod
     buildSpiderT $MODULEPATH > $HOME/.cache/lmod/spiderT.lua

     runLmod load a                  #44
     runLmod save my_A               #45
     runLmod purge                   #46
     runLmod restore my_A            #47

     runLmod purge                   #48
     runLmod load icc ifort          #49
     runLmod save my_intel           #50
     runLmod purge                   #51
     runLmod restore my_intel        #52

     HOME=$ORIG_HOME
     export HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv

     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/saverestore/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/saverestore/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/t1.result -t /Users/mcawood/Lmod/Lmod/rt/saverestore/t1/2024_11_07_13_03_06-Darwin-arm64-saverestore/t1.runtime results.csv
   