#!/bin/bash
# -*- shell-script -*-

packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/lars"; export testDir
messageFn="/Users/mcawood/Lmod/Lmod/rt/lars/t1/2024_11_06_15_50_29-Darwin-arm64-lars/message.lua"; export messageFn
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_06"; export tag
target=""; export target
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/lars/lars.tdesc"; export testdescriptFn
TARGET=""; export TARGET
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/lars/t1/2024_11_06_15_50_29-Darwin-arm64-lars/results.lua"; export cmdResultFn
packageName="rt"; export packageName
resultFn="/Users/mcawood/Lmod/Lmod/rt/lars/t1/2024_11_06_15_50_29-Darwin-arm64-lars/t1.result"; export resultFn
testName="lars"; export testName
idTag="t1"; export idTag
outputDir="/Users/mcawood/Lmod/Lmod/rt/lars/t1/2024_11_06_15_50_29-Darwin-arm64-lars"; export outputDir
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/lars/t1/2024_11_06_15_50_29-Darwin-arm64-lars/t1.runtime"; export runtimeFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/lars/mf/Core;     export MODULEPATH
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/lars/mf;     export MODULEPATH_ROOT

     RTM_SETTARG_CMD=":";               export RTM_SETTARG_CMD

     remove_generated_lmod_files

     runLmod --version          # 1
     runLmod load TACC          # 2
     runLmod list               # 3
     runLmod swap mvapich2 impi # 4
     runLmod list               # 5
     runLmod save               # 6
     runLmod purge              # 7
     runLmod restore            # 8
     runLmod list               # 9

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/lars/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/lars/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/lars/t1/2024_11_06_15_50_29-Darwin-arm64-lars/t1.result -t /Users/mcawood/Lmod/Lmod/rt/lars/t1/2024_11_06_15_50_29-Darwin-arm64-lars/t1.runtime results.csv
   