#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/cas_avail/t1/2024_10_17_14_37_12-Darwin-arm64-cas_avail/t1.result"; export resultFn
testName="cas_avail"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/cas_avail/cas_avail.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/cas_avail/t1/2024_10_17_14_37_12-Darwin-arm64-cas_avail/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/cas_avail/t1/2024_10_17_14_37_12-Darwin-arm64-cas_avail/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/cas_avail/t1/2024_10_17_14_37_12-Darwin-arm64-cas_avail/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/cas_avail"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/cas_avail/t1/2024_10_17_14_37_12-Darwin-arm64-cas_avail"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh
     unsetMT
     initStdEnvVars
     MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/cas_avail/mf;     export MODULEPATH_ROOT
     MODULEPATH=$MODULEPATH_ROOT/Core/; export MODULEPATH
     unset TERM

     remove_generated_lmod_files

     cp /Users/mcawood/Lmod/Lmod/init/lmodrc.lua .lmodrc.lua


     runLmod --version                # 1
     runLmod avail                    # 2
     runLmod use /Users/mcawood/Lmod/Lmod/rt/cas_avail/mf/kc     # 3
     runLmod avail                    # 4
     runLmod load matlab/R2015a       # 5
     runLmod list                     # 6

     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/cas_avail/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/cas_avail/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/cas_avail/t1/2024_10_17_14_37_12-Darwin-arm64-cas_avail/t1.result -t /Users/mcawood/Lmod/Lmod/rt/cas_avail/t1/2024_10_17_14_37_12-Darwin-arm64-cas_avail/t1.runtime results.csv
   