#!/bin/bash
# -*- shell-script -*-

projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
tag="2024_11_07"; export tag
idTag="t1"; export idTag
TARGET=""; export TARGET
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/use_w_sticky/t1/2024_11_07_13_03_06-Darwin-arm64-use_w_sticky/t1.runtime"; export runtimeFn
resultFn="/Users/mcawood/Lmod/Lmod/rt/use_w_sticky/t1/2024_11_07_13_03_06-Darwin-arm64-use_w_sticky/t1.result"; export resultFn
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
testDir="/Users/mcawood/Lmod/Lmod/rt/use_w_sticky"; export testDir
testName="use_w_sticky"; export testName
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/use_w_sticky/t1/2024_11_07_13_03_06-Darwin-arm64-use_w_sticky/message.lua"; export messageFn
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/use_w_sticky/use_w_sticky.tdesc"; export testdescriptFn
outputDir="/Users/mcawood/Lmod/Lmod/rt/use_w_sticky/t1/2024_11_07_13_03_06-Darwin-arm64-use_w_sticky"; export outputDir
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/use_w_sticky/t1/2024_11_07_13_03_06-Darwin-arm64-use_w_sticky/results.lua"; export cmdResultFn

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     export MODULEPATH_ROOT=/Users/mcawood/Lmod/Lmod/rt/use_w_sticky/mf
     export MODULEPATH=$MODULEPATH_ROOT/Core

     remove_generated_lmod_files

     runLmod --version                                   # 1
     runLmod load HPCBIOS                                # 2
     runLmod purge                                       # 3
     runLmod list                                        # 4
     unset MODULEPATH                                    # 5
     runLmod -T use /Users/mcawood/Lmod/Lmod/rt/use_w_sticky/mf/Other /Users/mcawood/Lmod/Lmod/rt/use_w_sticky/mf/A  # 6
     runBase echo MODULEPATH: $MODULEPATH 1>&2           # 7
     
     HOME=$ORIG_HOME
     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results  -bash  _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/use_w_sticky/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/use_w_sticky/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/use_w_sticky/t1/2024_11_07_13_03_06-Darwin-arm64-use_w_sticky/t1.result -t /Users/mcawood/Lmod/Lmod/rt/use_w_sticky/t1/2024_11_07_13_03_06-Darwin-arm64-use_w_sticky/t1.runtime results.csv
   