#!/bin/bash
# -*- shell-script -*-

resultFn="/Users/mcawood/Lmod/Lmod/rt/prereq/t1/2024_10_17_14_37_12-Darwin-arm64-prereq/t1.result"; export resultFn
testName="prereq"; export testName
testdescriptFn="/Users/mcawood/Lmod/Lmod/rt/prereq/prereq.tdesc"; export testdescriptFn
runtimeFn="/Users/mcawood/Lmod/Lmod/rt/prereq/t1/2024_10_17_14_37_12-Darwin-arm64-prereq/t1.runtime"; export runtimeFn
cmdResultFn="/Users/mcawood/Lmod/Lmod/rt/prereq/t1/2024_10_17_14_37_12-Darwin-arm64-prereq/results.lua"; export cmdResultFn
packageName="rt"; export packageName
target=""; export target
messageFn="/Users/mcawood/Lmod/Lmod/rt/prereq/t1/2024_10_17_14_37_12-Darwin-arm64-prereq/message.lua"; export messageFn
tag="2024_10_17"; export tag
testDir="/Users/mcawood/Lmod/Lmod/rt/prereq"; export testDir
projectDir="/Users/mcawood/Lmod/Lmod"; export projectDir
packageDir="/Users/mcawood/Lmod/Lmod/rt"; export packageDir
outputDir="/Users/mcawood/Lmod/Lmod/rt/prereq/t1/2024_10_17_14_37_12-Darwin-arm64-prereq"; export outputDir
TARGET=""; export TARGET
idTag="t1"; export idTag

     . /Users/mcawood/Lmod/Lmod/rt/common_funcs.sh

     unsetMT
     initStdEnvVars
     ORIGPATH=$PATH
     MODULEPATH=/Users/mcawood/Lmod/Lmod/rt/prereq/mf;          export MODULEPATH

     remove_generated_lmod_files

     runLmod --version          #  1
     runLmod load petsc         #  2
     runLmod load slepc/3.0.0   #  3
     runLmod unload slepc       #  4
     runLmod unload petsc       #  5
     runLmod load slepc         #  6
     runLmod load petsc/2.9.0   #  7
     runLmod load slepc         #  8
     runLmod load slepc/2.9.0   #  9
     runLmod load petsc/3.1.0   # 10
     runLmod load slepc         # 11
     runLmod unload slepc petsc # 12
     runLmod load petsc/3.1.0   # 13
     runLmod load slepc/2.9.0   # 14
     runLmod load junk/1.0      # 15
     runLmod load jdk32         # 16
     runLmod load junk/1.0      # 17

     PATH=$ORIGPATH
     export PATH
     HOME=$ORIG_HOME

     cat _stdout.[0-9][0-9][0-9] > _stdout.orig
     joinBase64Results -bash _stdout.orig _stdout.new
     cleanUp _stdout.new out.txt

     cat _stderr.[0-9][0-9][0-9] > _stderr.orig
     cleanUp _stderr.orig err.txt

     rm -f results.csv
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/prereq/out.txt out.txt
     wrapperDiff --csv results.csv /Users/mcawood/Lmod/Lmod/rt/prereq/err.txt err.txt
     testFinish -r /Users/mcawood/Lmod/Lmod/rt/prereq/t1/2024_10_17_14_37_12-Darwin-arm64-prereq/t1.result -t /Users/mcawood/Lmod/Lmod/rt/prereq/t1/2024_10_17_14_37_12-Darwin-arm64-prereq/t1.runtime results.csv
   